openapi: 3.0.0
info:
  title: Wizipragma API
  version: 1.0.0
  description: API para comunicaci贸n entre componentes

servers:
  - url: http://localhost:3000/api/v1
    description: Desarrollo local
  - url: https://api.wizipragma.com/api/v1
    description: Producci贸n

paths:
  /users:
    get:
      summary: Obtener lista de usuarios
      tags: [Users]
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
    
    post:
      summary: Crear nuevo usuario
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
      responses:
        '201':
          description: Usuario creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /agent/execute:
    post:
      summary: Ejecutar acci贸n del agente
      tags: [Agent]
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentRequest'
      responses:
        '200':
          description: Acci贸n ejecutada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '401':
          description: No autorizado
        '500':
          description: Error del servidor

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        role:
          type: string
          enum: [admin, developer, user]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    
    UserCreateRequest:
      type: object
      required:
        - email
        - name
        - password
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        password:
          type: string
          minLength: 8
        role:
          type: string
          enum: [developer, user]
    
    AgentRequest:
      type: object
      required:
        - action
        - parameters
      properties:
        id:
          type: string
        userId:
          type: string
        action:
          type: string
        parameters:
          type: object
        timestamp:
          type: string
          format: date-time
    
    AgentResponse:
      type: object
      properties:
        requestId:
          type: string
        status:
          type: string
          enum: [success, error, pending]
        result:
          type: object
        error:
          $ref: '#/components/schemas/ErrorDetail'
        timestamp:
          type: string
          format: date-time
    
    ErrorDetail:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
        correlationId:
          type: string
    
    ApiResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
        error:
          $ref: '#/components/schemas/ErrorDetail'
        metadata:
          type: object

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
