#!/bin/bash
# Configure AWS Bedrock AgentCore for CENTLI
# This script creates the AgentCore agent with Claude 3.7 Sonnet

set -e

echo "=========================================="
echo "CENTLI - Bedrock AgentCore Configuration"
echo "=========================================="
echo ""

# Configuration
PROFILE="777937796305_Ps-HackatonAgentic-Mexico"
REGION="us-east-1"
AGENT_NAME="centli-agentcore"
FOUNDATION_MODEL="anthropic.claude-3-5-sonnet-20241022-v2:0"

echo "Configuration:"
echo "  AWS Profile: $PROFILE"
echo "  AWS Region: $REGION"
echo "  Agent Name: $AGENT_NAME"
echo "  Foundation Model: $FOUNDATION_MODEL"
echo ""

# Step 1: Create AgentCore Agent
echo "Step 1: Creating Bedrock Agent..."
echo ""
echo "⚠️  MANUAL STEP REQUIRED ⚠️"
echo ""
echo "Please create the Bedrock Agent manually via AWS Console:"
echo ""
echo "1. Go to AWS Bedrock Console > Agents"
echo "2. Click 'Create Agent'"
echo "3. Configure:"
echo "   - Agent name: $AGENT_NAME"
echo "   - Agent description: CENTLI Multimodal Banking Assistant"
echo "   - Foundation model: $FOUNDATION_MODEL"
echo "   - Instructions: You are a helpful banking assistant that helps users with"
echo "     financial transactions, product information, and account management."
echo "     You can process text, voice, and image inputs."
echo ""
echo "4. Enable Managed Memory:"
echo "   - Go to Agent > Memory"
echo "   - Enable 'Managed Memory'"
echo "   - Set retention: Session-based"
echo ""
echo "5. Configure Action Groups (to be added in Unit 3):"
echo "   - Core Banking Actions"
echo "   - Marketplace Actions"
echo "   - CRM Actions"
echo ""
echo "6. Create Agent Alias:"
echo "   - Alias name: prod"
echo "   - Description: Production alias for hackathon"
echo ""
echo "7. Note the Agent ID and Alias ID"
echo ""

# Step 2: Update Lambda environment variable
echo "Step 2: Update Lambda Function with Agent ID"
echo ""
echo "After creating the agent, run:"
echo ""
echo "aws lambda update-function-configuration \\"
echo "    --profile $PROFILE \\"
echo "    --region $REGION \\"
echo "    --function-name centli-app-message \\"
echo "    --environment Variables='{AGENTCORE_ID=<YOUR_AGENT_ID>,SESSIONS_TABLE=centli-sessions,EVENT_BUS_NAME=centli-event-bus,ASSETS_BUCKET=centli-assets-777937796305,LOG_LEVEL=INFO,AWS_ACCOUNT_ID=777937796305}'"
echo ""
echo "Replace <YOUR_AGENT_ID> with the actual Agent ID from step 1"
echo ""

# Step 3: Verification
echo "Step 3: Verification"
echo ""
echo "To verify the configuration:"
echo ""
echo "1. Check Agent status:"
echo "   aws bedrock-agent list-agents --profile $PROFILE --region $REGION"
echo ""
echo "2. Check Lambda environment:"
echo "   aws lambda get-function-configuration \\"
echo "       --profile $PROFILE \\"
echo "       --region $REGION \\"
echo "       --function-name centli-app-message \\"
echo "       --query 'Environment.Variables.AGENTCORE_ID'"
echo ""

echo "=========================================="
echo "Configuration Instructions Complete"
echo "=========================================="
echo ""
echo "⚠️  Remember to complete the manual steps above!"
